### ISSUE TITLE
BGSBot not retrieving data

### ISSUE THREAD

**Issue by DaleFranks** [Elite-Kode/bgsbot#63]
BGSBot is returning data inconsistently. For instance the command 

@BGSBot systemstatus get lft 424
returns "Eeek! problems :frowning:"
while the command 
BGSBot systemstatus get gliese 3371
returns the system BGS data.

Similarly, 
@BGSBot factionstatus get revolutionary lhs 220 confederacy
works fine while
@BGSBot bgsreport get
returns "Um...sorry couldn't do that" even though the report was working yesterday, and has LFT 424 being monitored as system primary.

This just started today, Yesterday, BGSBot was working as expected.

![image](https://user-images.githubusercontent.com/31809492/116285613-24624700-a743-11eb-8968-02525f4f5e50.png)

**Comment by SayakMukhopadhyay** [comment]
Hi, I just checked it right now and I am able to fetch data for lft 424. Can you verify if this is still am issue?

**Comment by b2soft** [comment]
I habe the same issue
![image](https://user-images.githubusercontent.com/6034932/116305555-9c188c00-a7ac-11eb-8251-dbcb925eaf4b.png)

**Comment by SayakMukhopadhyay** [comment]
Fixed by https://github.com/Elite-Kode/elitebgs/commit/62d63cf808700a7d15df424a05728f73c75180c6
